# Generated by Django 5.0.2 on 2024-02-29 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_rgb_productcolor_color_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productcolor',
            unique_together={('name', 'color_code', 'size', 'product')},
        ),
    ]
