# Generated by Django 5.0.2 on 2024-03-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productcolor_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('', 'Select Type'), ('0', 'T-Shirt'), ('1', 'Sweat Pants'), ('2', 'Sweaters'), ('3', 'Accessories')], max_length=200),
        ),
    ]
