# Generated by Django 5.0.2 on 2024-03-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('', 'Select Type'), ('1', 'T-Shirt'), ('2', 'Sweat Pants'), ('3', 'Sweaters'), ('4', 'Accessories')], max_length=200),
        ),
    ]
