# Generated by Django 5.0.2 on 2024-03-03 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productsize',
            unique_together={('size', 'product')},
        ),
    ]
